import { ModifierType } from "./types";

export const MODIFIER_CATALOG_FLAT = [
  { type: ModifierType.OUTLINE, label: "Outline", cat: "Shape" },
  { type: ModifierType.STRETCH, label: "Stretch", cat: "Distort" },
  { type: ModifierType.REPEATER, label: "Repeater", cat: "Pattern" },
  {
    type: ModifierType.PARTICLE_DISSOLVE,
    label: "Particle Dissolve",
    cat: "Physics",
  },
  { type: ModifierType.SPRING, label: "Spring", cat: "Physics" },
  { type: ModifierType.WAVE, label: "Wave", cat: "Distort" },
  { type: ModifierType.PARALLAX, label: "Parallax", cat: "Motion" },
  { type: ModifierType.AI_FILL, label: "AI Fill", cat: "AI" },
  { type: ModifierType.GLITCH, label: "Glitch", cat: "Effect" },
  { type: ModifierType.REFRACTION, label: "Refraction", cat: "Glass" },
  { type: ModifierType.HALFTONE_LUMA, label: "Halftone", cat: "Style" },
  { type: ModifierType.EXTRUDE, label: "Extrude 3D", cat: "3D" },
  {
    type: ModifierType.BRIGHTNESS_CONTRAST,
    label: "Bright/Contr",
    cat: "Color",
  },
  { type: ModifierType.GRADIENT_MAP, label: "Gradient Map", cat: "Color" },
  { type: ModifierType.PERTURB, label: "Perturb", cat: "Distort" },
  { type: ModifierType.REMOVE_BACKGROUND, label: "Remove BG", cat: "AI" },
  { type: ModifierType.SPLIT_TO_LAYERS, label: "Split Layers", cat: "Util" },
  { type: ModifierType.PEN_STROKES, label: "Pen Strokes", cat: "Style" },
  { type: ModifierType.EMBOSS, label: "Emboss", cat: "Style" },
  { type: ModifierType.DROP_SHADOW, label: "Drop Shadow", cat: "Style" },
  { type: ModifierType.INNER_SHADOW, label: "Inner Shadow", cat: "Style" },
  { type: ModifierType.BEVEL_EMBOSS, label: "Bevel", cat: "3D" },
  { type: ModifierType.COLOR_OVERLAY, label: "Color Overlay", cat: "Color" },
  { type: ModifierType.NOISE, label: "Noise", cat: "Effect" },
  { type: ModifierType.GAUSSIAN_BLUR, label: "Gaussian Blur", cat: "Blur" },
  { type: ModifierType.MOTION_BLUR, label: "Motion Blur", cat: "Blur" },
  { type: ModifierType.RADIAL_BLUR, label: "Radial Blur", cat: "Blur" },
  { type: ModifierType.LIQUIFY, label: "Liquify", cat: "Distort" },
  { type: ModifierType.DISPLACEMENT_MAP, label: "Displace", cat: "Distort" },
  { type: ModifierType.THRESHOLD, label: "Threshold", cat: "Color" },
  { type: ModifierType.INVERT, label: "Invert", cat: "Color" },
  { type: ModifierType.POSTERIZE, label: "Posterize", cat: "Color" },
  { type: ModifierType.HUE_SATURATION, label: "Hue/Sat", cat: "Color" },
  { type: ModifierType.CURVES, label: "Curves", cat: "Color" },
  { type: ModifierType.VIGNETTE, label: "Vignette", cat: "Effect" },
  { type: ModifierType.LENS_FLARE, label: "Lens Flare", cat: "Light" },
  { type: ModifierType.BLOOM, label: "Bloom", cat: "Light" },
  {
    type: ModifierType.CHROMATIC_ABERRATION,
    label: "Chromatic",
    cat: "Effect",
  },
  { type: ModifierType.SHARPEN, label: "Sharpen", cat: "Effect" },
  { type: ModifierType.TILT_SHIFT, label: "Tilt Shift", cat: "Blur" },
  { type: ModifierType.DITHER, label: "Dither", cat: "Retro" },
  { type: ModifierType.PIXELATE, label: "Pixelate", cat: "Retro" },
  { type: ModifierType.KALEIDOSCOPE, label: "Kaleidoscope", cat: "Effect" },
  { type: ModifierType.MODIFIER_GROUP, label: "Group", cat: "Util" },
];
